# Dependencies
markdown:         kramdown
highlighter:      rouge

github:
  - metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - rakefile
  - vendor

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

gems:
  - jekyll-paginate
  - jekyll-minify-html
  - jekyll-redirect-from
  - jekyll-sitemap

# Permalinks
permalink:        /:title

# Setup
title:            mhl
tagline:          ''
description:      '<a href="http://twitter.com/LeonardMH">@twitter</a><br /><a href="http://github.com/LeonardMH">@github</a>'
url:              http://michaelhleonard.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
version:          2.1.0

